server:
  port: 8080
  undertow:
    buffer-size: 1024
    direct-buffers: true
  servlet:
    context-path: /
#配置数据库信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.31.15.127:3306/blog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: blog
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: HiKari
      max-lifetime: 300000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      idle-timeout: 30000
      minimum-idle: 3
      maximum-pool-size: 20
  jackson:
    time-zone: GMT+8
    date-format: yyyy年MM月dd日 HH:mm:ss
  redis:
    host: 118.31.15.127
    database: 1
    timeout: 1000
  mail:
    host: smtp.qq.com
    username: 1270857044@qq.com
    password: gncatexfmfyvjihg
    port: 465
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            socketFactory:
              port: 465
              class: javax.net.ssl.SSLSocketFactory
  thymeleaf:
    servlet:
      content-type: text/html
    cache: false
    encoding: utf-8
    prefix: classpath:/templates/
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
  #静态资源路径配置
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
#指定mybatisPlus扫描的xml文件
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-column-label: true
  #    cache-enabled: true
  #    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**.xml
  type-aliases-package: com.spring.myblog.entity

# PageHelper分页插件
pagehelper:
  helperDialect: mysql

rocketmq:
  name-server: 47.98.209.26:9876
  producer:
    group: myblog
    # 发送同步消息失败时，重试次数，默认是 2
    retry-times-when-send-failed: 2
    # 发送异步消息失败时，重试次数，默认是 2
    retry-times-when-send-async-failed: 2
    # 发送消息超时时间，默认是 3s
    send-message-timeout: 1000

logging:
  level:
    org.springframework: warn

