server:
  port: 8082
#配置数据库信息
spring:
  application:
    name: file
  jackson:
    time-zone: GMT+8
    date-format: yyyy年MM月dd日 HH:mm:ss
  redis:
    host: 118.31.15.127
    database: 0
    timeout: 1000
    password: Zkm229544074

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

rocketmq:
  name-server: 47.98.209.26:9876
  producer:
    group: myblog
    # 发送同步消息失败时，重试次数，默认是 2
    retry-times-when-send-failed: 2
    # 发送异步消息失败时，重试次数，默认是 2
    retry-times-when-send-async-failed: 2
    # 发送消息超时时间，默认是 3s
    send-message-timeout: 3000

logging:
  level:
    org.springframework: warn

